Initial version

diff --git a/opt/resource/out b/opt/resource/out
--- a/opt/resource/out
+++ b/opt/resource/out
@@ -2,83 +2,41 @@
 
 set -e
 
-exec 3>&1 # make stdout available as fd 3 for the result
-exec 1>&2 # redirect all output to stderr for logging
+{    
+    set -x
+    
+    destination=$1
+    cd $destination
 
-source $(dirname $0)/common.sh
+    TMPDIR=${TMPDIR:-/tmp}
+    payload=$(mktemp $TMPDIR/concourse-flyway-resource.XXXXXX)
+    cat > $payload <&0
+    
 
-destination=$1
-cd $destination
+    params=$(jq -r '.params // ""' < $payload)
+    source=$(jq -r '.source // ""' < $payload)
 
-payload=$(mktemp $TMPDIR/concourse-serverless-resource.XXXXXX)
-cat > $payload <&0
+    migrate=$(echo $params | jq -r '.migrate // false')
+    repair=$(echo $params | jq -r '.repair // false')
+    migrations_dir=$(echo $params | jq -r '.migrations_dir // ""')
 
-params=$(jq -r '.params // ""' < $payload)
-source=$(jq -r '.source // ""' < $payload)
-
-deploy=$(echo $params | jq -r '.deploy // false')
-remove=$(echo $params | jq -r '.remove // false')
-stage=$(echo $params | jq -r '.stage // ""')
-
-if [ -z $stage ]; then
-    echo "invalid params (missing stage):" >&2
-    cat $params >&2
-    exit 1
-fi
-
-if [ $deploy = "false" ] && [ $remove = "false" ]; then
-    echo "invalid params (either deploy or remove must be true):" >&2
-    cat $params >&2
-    exit 1
-fi
-
-
-region=$(echo $source | jq -r '.region_name // ""')
-npm_install=$(echo $params | jq -r '.npm_install // false')
-npm_build=$(echo $params | jq -r '.npm_build // false')
-npm_prefix=$(echo $params | jq -r '.npm_prefix // ""')
-
-echo "region: $region || npm_build: $npm_build || npm_install: $npm_install || npm_prefix: $npm_prefix"
-
-if [ $npm_install = "true" ]; then
-    if [ -z $npm_prefix ]; then
-        npm install
-    else
-        npm install --prefix $npm_prefix
+    if [ $migrate = "false" ] && [ $repair = "false" ]; then
+        echo "invalid params (either migrate or repair must be true):" >&2
+        cat $params >&2
+        exit 1
     fi
-fi
 
-if [ $npm_build  = "true" ]; then
-        if [ -z $npm_prefix ]; then
-        npm build
-    else
-        npm build --prefix $npm_prefix
+    db_url=$(echo $source | jq -r '.db_url // ""')
+    db_user=$(echo $source | jq -r '.db_user // ""')
+    db_password=$(echo $source | jq -r '.db_password // ""')    
+
+    if [ $migrate = "true" ]; then
+        flyway migrate -url="$db_url"  \
+                      -user="$db_user" \
+                      -password="$db_password" \
+                      -locations="filesystem:$migrations_dir" \
+                      -X
     fi
-fi
+} >&2
 
-serverless_dir=$(echo $params | jq -r '.serverless // ""')
-
-if [ -z $serverless_dir ]; then
-    echo "invalid params (must set serverless): " >&2
-    cat $params >&2
-    exit 1
-fi
-
-cd $serverless_dir
-
-set_serverless_credentials "$source"
-
-regionflag=""
-if [ ! -z $region ]; then
-    regionflag="--region $region"
-fi
-
-if [ $deploy = "true" ]; then
-    serverless deploy -v --stage $stage $regionflag
-    jq -n '{"version": ""}'
-fi
-
-if [ $remove = "true" ]; then
-    serverless remove -v --stage $stage $regionflag
-    jq -n '{}'
-fi
+jq -n '{"version": { "ref": "'`date +"%m-%d-%Y_%H-%M-%S"`'"} }'
